### ISSUE TITLE
Debug tests are not deleting the binary and the C file after usage

### ISSUE THREAD

**Issue by rauletorresc** [PennyLaneAI/catalyst#1046]
* *Description of the issue:* After running `make test-frontend` either `test_executable_generation` or `test_executable_generation_without_precompiled_function` from `test_debug.py` are leaving two ghost files undeleted: `f.out` and `main.c`

* *Expected behavior:* There shouldn't be any new files in the Catalyst root folder after running  `make test-frontend`.

* *Actual behavior:* (What actually happens) The two mentioned files are there in the Catalyst root folder.

* *Reproduces how often:* (What percentage of the time does it reproduce?) Always.

* *Catalyst commit:* https://github.com/PennyLaneAI/catalyst/commit/b95d8622b133071d02a08783ccba4f736d4d43f9

**Comment by paul0403** [comment]
Ahh, so that's what those two are...

**Comment by rauletorresc** [comment]
Closing as fixed
