### ISSUE TITLE
Additional library required to install from source on Linux

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/catalyst#1084]
I just tried installed from source (`v0.8.0-rc` branch) on two different Linux machines running Ubuntu 24.04 (one is a recent clean install). I was running in new virtual environments created with Python's built-in `venv` functionality.

I followed the build instructions [here](https://docs.pennylane.ai/projects/catalyst/en/stable/dev/installation.html), including the command to install dependencies via `apt`. On both machines, I ran into the error below, which was solved by installing an additional package:

```
sudo apt install python-dev-is-python3
```
Possibly this needs to be included in the docs? Let me know if there is any other info that would be useful (I have one more computer I can try on!).

```
-- Build files have been written to: /home/olivia/Code/catalyst/runtime/build
cmake --build /home/olivia/Code/catalyst/runtime//build --target rt_capi rtd_dummy rtd_lightning rtd_openqasm -j12
[3/36] Building CXX object lib/capi/CMakeFiles/catalyst_qir_qis_obj.dir/RuntimeCAPI.cpp.o
FAILED: lib/capi/CMakeFiles/catalyst_qir_qis_obj.dir/RuntimeCAPI.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DLIBREGISTRY=\"catalyst_callback_registry.cpython-312-x86_64-linux-gnu.so\" -I/home/olivia/Code/catalyst/runtime/lib/capi/. -I/home/olivia/Code/catalyst/runtime/lib/capi -I/home/olivia/Code/catalyst/runtime/include -I/home/olivia/Code/catalyst/runtime/utils -I/home/olivia/Code/catalyst/runtime/build/lib/capi/mlir/ExecutionEngine/../.. -I/home/olivia/Code/catalyst/runtime/../mlir/lib/Driver -isystem /home/olivia/.venv/shortalyst/lib/python3.12/site-packages/pybind11/include -isystem /usr/include/python3.12 -O2 -g -DNDEBUG -std=gnu++20 -fPIC -Werror -Wall -Wno-unused-parameter -MD -MT lib/capi/CMakeFiles/catalyst_qir_qis_obj.dir/RuntimeCAPI.cpp.o -MF lib/capi/CMakeFiles/catalyst_qir_qis_obj.dir/RuntimeCAPI.cpp.o.d -o lib/capi/CMakeFiles/catalyst_qir_qis_obj.dir/RuntimeCAPI.cpp.o -c /home/olivia/Code/catalyst/runtime/lib/capi/RuntimeCAPI.cpp
In file included from /home/olivia/Code/catalyst/runtime/lib/capi/RuntimeCAPI.cpp:31:
In file included from /home/olivia/Code/catalyst/runtime/lib/capi/ExecutionContext.hpp:29:
In file included from /home/olivia/Code/catalyst/runtime/utils/Python.hpp:20:
In file included from /home/olivia/.venv/shortalyst/lib/python3.12/site-packages/pybind11/include/pybind11/embed.h:12:
In file included from /home/olivia/.venv/shortalyst/lib/python3.12/site-packages/pybind11/include/pybind11/pybind11.h:13:
In file included from /home/olivia/.venv/shortalyst/lib/python3.12/site-packages/pybind11/include/pybind11/detail/class.h:12:
In file included from /home/olivia/.venv/shortalyst/lib/python3.12/site-packages/pybind11/include/pybind11/attr.h:13:
/home/olivia/.venv/shortalyst/lib/python3.12/site-packages/pybind11/include/pybind11/detail/common.h:274:10: fatal error: 'Python.h' file not found
  274 | #include <Python.h>
      |          ^~~~~~~~~~
1 error generated.
[14/36] Building CXX object _deps/pennylane_lightnin...ster_kernels_avx512.dir/RegisterKernels_AVX512.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:117: runtime] Error 1
make[1]: Leaving directory '/home/olivia/Code/catalyst/runtime'
make: *** [Makefile:113: runtime] Error 2
```

**Comment by dime10** [comment]
Thanks for reporting this @glassnotes! I'm not aware of this requirement but we'll look into it and update the docs accordingly :)

**Comment by josh146** [comment]
It looks like `python-dev-is-python3` is simply a shim package 🤔 

https://packages.debian.org/bullseye/python-dev-is-python3

> Starting with the Debian 11 (bullseye) and Ubuntu 20.04 LTS (focal) releases, all python packages use explicit python3 or python2 interpreter and do not use unversioned /usr/bin/python-config at all. Some third-party code is now predominantly python3 based, yet may use /usr/bin/python-config.
>
> This is a convenience package which ships a symlink to point /usr/bin/python-config script at the current default python3. It may improve compatibility with other modern systems, whilst breaking some obsolete or 3rd-party software.
>
> No packages may declare dependencies on this package.

**Comment by dime10** [comment]
Yeah we can probably fix this on our side without requiring users to install the package 🤔

**Comment by dime10** [comment]
Actually, I wonder if we need to tell users to install the python-dev package 🤔 @glassnotes Was `python-dev` (or `python3-dev` / `python3.*-dev`) already installed for you when you got the error?

**Comment by glassnotes** [comment]
None of them were already installed, and when I tried to install `python-dev`, apt bounced me to the `python-dev-is-python3` option.

**Comment by dime10** [comment]
Ah interesting, I think we do have a dependency on the `dev` package now.

**Comment by glassnotes** [comment]
Actually my initial thought was that it was a path problem, because pybind11 couldn't find the headers. But searching for the error led to the install suggestion, which worked, so I didn't pursue it further.

**Comment by dime10** [comment]
It looks like `python-dev-is-python3` installs `python3-dev`, so maybe that was the solution? If you uninstall `python-dev-is-python3` (leaving `python3-dev` in place), does it still work or does the error come back?

**Comment by glassnotes** [comment]
I believe this works, yes - I tried uninstalling/reinstalling it on a machine from yesterday, and on a third machine with `python3-dev` installed, but not `python-dev-is-python3`.

**Comment by rauletorresc** [comment]
I can confirm what was reported by @glassnotes: on a clean installation of Ubuntu 24.04, you need the  `python-dev-is-python3` package. I will update the documentation accordingly.
