### ISSUE TITLE
Improve handling of execution configs, especially as default arguments to other functions

### ISSUE THREAD

**Issue by joeycarter** [PennyLaneAI/catalyst#1135]
We noticed in #1117 that using `qml.devices.DefaultExecutionConfig`, which is a mutable, global object, as default arguments to other functions caused a test to fail in some contexts, most likely because of a race condition where some other function from another test had modified this global variable.

This [guide on common Python gotchas](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) explains the fundamental issue, and recommends to generally avoid patterns like

```python
def append_to(element, to=[]):
    to.append(element)
    return to
```

where a (mutable) empty list is provided as the default argument to the `to` input argument, and prefer the following pattern instead:

```python
def append_to(element, to=None):
    if to is None:
        to = []
    to.append(element)
    return to
```

[This search query](https://github.com/search?q=repo%3APennyLaneAI%2Fcatalyst%20defaultexecutionconfig&type=code) shows where `qml.devices.DefaultExecutionConfig` is used as a default argument in the Catalyst code base. We should refactor this code to avoid the mutable-default-argument gotcha.

**Comment by paul0403** [comment]
Note on the somewhat unexpected behavior of mutable default arguments:
```python
def f(x=[]):
   x.append(0)
return x
 
>>> f()
[0]
>>> f()  #  a "sane" person would expect [0]
[0, 0]
>>> f()  #  a "sane" person would expect [0]
[0, 0, 0]

```

**Comment by joeycarter** [comment]
Small implementation detail: I think we'll need to use `deepcopy` on `DefaultExecutionConfig`, rather than `dataclass.replace`, which performs a shallow copy. This is because several of the config parameters are stored as dictionaries, which should also not be modified in the global object.

**Comment by dime10** [comment]
> Small implementation detail: I think we'll need to use `deepcopy` on `DefaultExecutionConfig`, rather than `dataclass.replace`, which performs a shallow copy. This is because several of the config parameters are stored as dictionaries, which should also not be modified in the global object.

Hmm, we might want to bring in @albi3ro for this question, but `replace` is the strategy they use in PennyLane. I think `deepcopy` would be an issue once the config is immutable because the copy will still be immutable.

**Comment by albi3ro** [comment]
I actually didn't even realize that `replace` was a shallow copy, so that is even more of an issue than I was originally thinking.

Summarizing some discussions, I think our path forward should be:

1) Use replace to update properties, in addition to `gradient_keyword_args` and `device_options`.
2) Defaulting to `execution_config: Optional[ExecutionConfig] = None`, instead of `DefaultExecutionConfig`.
3) Making `ExecutionConfig` freezable and/or frozen.

Thanks for finding all these things, and I'm sorry for putting this design in to begin with. Hopefully we can fix these mistakes in the next few months.

**Comment by joeycarter** [comment]
Thanks @albi3ro! I agree, I think this is the way forward.
