### ISSUE TITLE
[MLIR] Re-enable buffer deallocation

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#122]
Take into account aliasing when passing memrefs as parameters to other functions and returning them.

**Comment by dime10** [comment]
This was addressed upstream in https://reviews.llvm.org/D150546

**Comment by erick-xanadu** [comment]
With the recent LLVM update, I think this is now feasible.

**Comment by erick-xanadu** [comment]
Just investigated a little bit here: re-enabling deallocation triggers a bug in several of the gradient tests (with particular emphasis on parameter shift and adjoint). The stacktrace for the error is unrelated to gradients though.

**Comment by erick-xanadu** [comment]
I think I have narrowed at least a sub problem here. At some point during the bufferization pipeline, in the argmap function there's a `memref::CastOp` (`%cast = memref.cast %alloc : memref<32xf64> to memref<?xf64>`) The deallocation pass will schedule a deallocation for `%alloc` when `%cast` is still live in the heap `memref.store %cast, %alloc_0[] : memref<memref<?xf64>>`. Essentially `%alloc` and `%cast` alias, but `%alloc` is freed leading to erros in the gradient tests.

This is consistent (somewhat) with the MLIR documentation on [deallocation](https://mlir.llvm.org/docs/Dialects/MemRef/#memrefdealloc-memrefdeallocop)

> The dealloc operation frees the region of memory referenced by a memref which was originally created by the alloc operation. The dealloc operation should not be called on memrefs which alias an alloc’d memref (e.g. memrefs returned by view operations).

Here the documentation says that we shouldn't free `%cast` (since that would mean that `%alloc` is also freed). But I would argue that `%cast` should also not be dealloc'ed.
