### ISSUE TITLE
Bug when applying a double ``qml.adjoint``

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/catalyst#1301]
Double adjoint does not work correctly. It seems that it simply applies one adjoint.
In the following script we can compare the correct result in lightning with an incorrect result in catalyst.

```python
device = qml.device("lightning.qubit", wires=1)
def circuit():
    qml.Hadamard(0)
    qml.adjoint(qml.adjoint(qml.S(0)))
    return qml.state()

interpreted_fn = qml.QNode(circuit, device)
jitted_fn = qjit(interpreted_fn)

print(np.round(interpreted_fn(), 2))
print(np.round(jitted_fn(), 2))
```

```
[0.71+0.j   0.  +0.71j]
 [0.71+0.j   0.  -0.71j]
```

It seems to be a recently introduced bug as it worked correctly before.

qml.about()

```

Platform info:           macOS-14.6.1-arm64-arm-64bit
Python version:          3.9.6
Numpy version:           1.26.4
Scipy version:           1.12.0
Installed devices:
- default.clifford (PennyLane-0.40.0.dev12)
- default.gaussian (PennyLane-0.40.0.dev12)
- default.mixed (PennyLane-0.40.0.dev12)
- default.qubit (PennyLane-0.40.0.dev12)
- default.qutrit (PennyLane-0.40.0.dev12)
- default.qutrit.mixed (PennyLane-0.40.0.dev12)
- default.tensor (PennyLane-0.40.0.dev12)
- null.qubit (PennyLane-0.40.0.dev12)
- reference.qubit (PennyLane-0.40.0.dev12)
- lightning.qubit (PennyLane-Lightning-0.38.0)
- nvidia.custatevec (PennyLane-Catalyst-0.8.1)
- nvidia.cutensornet (PennyLane-Catalyst-0.8.1)
- oqc.cloud (PennyLane-Catalyst-0.8.1)
- softwareq.qpp (PennyLane-Catalyst-0.8.1)

```

**Comment by dime10** [comment]
Do you know when it was still working? I can confirm that nested adjoint operator instances (like `Adjoint(Adjoint(S))`) do not get captured correctly in Catalyst. It could be that before we relied on simplification of calls like `qml.adjoint(qml.adjoint(*))` by PennyLane, but we will look into this!

**Comment by josh146** [comment]
It must be related to this:

https://github.com/PennyLaneAI/catalyst/blob/697e4d1ff77bedbd31a8689a8939f2374d55cb92/frontend/test/pytest/test_adjoint.py#L1472-L1475

**Comment by KetpuntoG** [comment]
> Do you know when it was still working? I can confirm that nested adjoint operator instances (like `Adjoint(Adjoint(S))`) do not get captured correctly in Catalyst. It could be that before we relied on simplification of calls like `qml.adjoint(qml.adjoint(*))` by PennyLane, but we will look into this!

I am not sure because I updated but I would say the last time I installed catalyst was 3 months ago

**Comment by dime10** [comment]
@josh146 That's a slightly different thing, it's merely that in the test case you link to the adjoint will not be an instance of PennyLane's `Adjoint` class, but instead an instance of Catalyst's `HybridAdjoint` class. Not a big deal, it's just that the original test as written does not pass (since it checks the object classes).

**Comment by josh146** [comment]
Got it :+1:

**Comment by dime10** [comment]
I think this should fix the issue, it would just need proper testing and polish: https://github.com/PennyLaneAI/catalyst/pull/1302

**Comment by dime10** [comment]
Just found out that this broke starting with version 0.39 (so last release)
