### ISSUE TITLE
Remove cross-compatiblity wheel tests.

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#144]

**Comment by maliasadi** [comment]
A clear title is better than long encrypted descriptions :sweat_smile:

**Comment by maliasadi** [comment]
This should be related to the new dependency of Catalyst's frontend to `pybind11`. We can fix this closer to the release.

**Comment by dime10** [comment]
Just confirming, but we now expect the cross-version tests to always fail so we can remove them right?
