### ISSUE TITLE
[Frontend] Compute the JVP of only specific argnums.

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/catalyst#148]
When using `catalyst.jvp`, you sometimes may only want the JVP of only specific argnums. `catalyst.jvp` supports an `argnum` argument, however, I cannot seem to get it to work:

```python
dev = qml.device("lightning.qubit", wires=2)

@qjit
@qml.qnode(dev)
def circuit(params, n):
    
    def ansatz(i, x):
        qml.RX(x[i, 0], wires=0)
        qml.RY(x[i, 1], wires=1)
        qml.CNOT(wires=[0, 1])
        return x

    catalyst.for_loop(0, n, 1)(ansatz)(params)

    return qml.expval(qml.PauliZ(1))

@qjit
def jvp(primals, tangents):
    return catalyst.jvp(circuit, [primals, 2], [tangents, np.zeros([])], argnum=0)
```

```pycon
>>> params = jnp.array([[0.54, 0.3154], [0.654, 0.123]])
>>> dy = jnp.ones((2, 2))
>>> jvp(params, dy)
CalledProcessError: Command '['/home/ec2-user/anaconda3/envs/Braket/lib/python3.10/site-packages/catalyst/bin/quantum-opt', '--lower-gradients', '/tmp/tmpp09x_7_z/jvp.nohlo.mlir', '-o', '/tmp/tmpp09x_7_z/jvp.nohlo.opt.mlir']' returned non-zero exit status 1.
```

When using `jax.jvp`, there is no `argnum` argument; as far as I can tell, you simply need to specify an empty tangent vector (with dtype `float0` if the corresponding primal is an integer) to avoid computation of that argument:

```pycon
>>> jax.jvp(circuit.qfunc, (params, 2), (jnp.ones((2, 2)), np.zeros([], dtype=jax.float0))
(Array(0.76127544, dtype=float64), Array(-0.73995881, dtype=float64))
```

**Comment by grwlf** [comment]
@josh146 I believe this behavior was expected. The docstring of the `catalyst.jvp` function says:

* params (List[Array]): List (or a tuple) of the fnuction arguments specifying the point to calculate JVP at. A subset of these parameters are declared as differentiable by listing their indices in the ``argnum`` parameter.
* tangents(List[Array]): List (or a tuple) of tangent values to use in JVP. **The list size and shapes must match the ones of differentiable params.**

When you specify `arnum=0` you declare that only the 1st argument is the differentiable. So the `tangents` parameter must contain exactly one value. 

It is true that `catalyst.jvp/vjp` differ from the jax version in a number of ways. I suggest at least to change the label from `bug` to some other type.

**Comment by josh146** [comment]
Thanks @grwlf! Do you have a code example to show how my example above would work with the Catalyst definition? It would be great to also add an example to the docstring.

**Comment by dime10** [comment]
I'll let @josh146 decide if #191 adequately resolves this issue.

**Comment by josh146** [comment]
Thanks @grwlf! This resolves the issue from my end.

Note that, when we try and integrate `catalyst.jvp` into the `@jax.custom_jvp` decorator, we may discover some other bugs/difficulties due to our jvp function signature not matching the JAX one, but this is something we will find out down the line :)
