### ISSUE TITLE
Compound expressions as conditions in `catalyst.cond` is not supported

### ISSUE THREAD

**Issue by maliasadi** [PennyLaneAI/catalyst#226]
Catalyst doesn't support compound expressions as conditions. Running the following example will raise a `jax.errors.ConcretizationTypeError`. 

``` python
@qjit
@qml.qnode(qml.device(backend, wires=1))
def circuit(x):
    @cond(x > 4 or True)
    def cond_fn():
        qml.PauliX(wires=0)

    cond_fn()

    return measure(wires=0)

circuit(2) 
```
``` console
E       jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape bool[].
E       The problem arose with the `bool` function. 
```

**Comment by josh146** [comment]
Thanks @maliasadi! Actually @dime10 this could be a new class of test conditions

**Comment by dime10** [comment]
This is expected JAX behaviour. Built-in Boolean Python functions do not work on JAX tracers, and users have to use `jax.numpy.logical_and` instead.

It's on our roadmap for autograph though as a QOL improvement (see https://app.shortcut.com/xanaduai/story/41303/add-the-ability-to-capture-logical-and-and-or-statements).

**Comment by dime10** [comment]
Support for this was now added in #325.
