### ISSUE TITLE
[Dynamic shapes] Raise an exception if shape is not an integer

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#378]
* *Expected behavior:* Shapes are integral values. Therefore an error should be raised if non-integral values are used.

* *Actual behavior:* Silently a rounding function (possibly floor) is used.

* *Reproduces how often:* Always

```python
   def f(x):
        return jnp.empty(shape=[2, x], dtype=int)

    assert qjit(f)(3.1).shape == (2, 3)
    assert qjit(f)(4.9).shape == (2, 4)
```

**Comment by erick-xanadu** [comment]
This is fixed in mainstream JAX https://github.com/google/jax/issues?q=is%3Aissue+author%3Aerick-xanadu+is%3Aclosed . We should close it once we move to a new release of JAX that has this commit.

**Comment by dime10** [comment]
Fixed upstream
