### ISSUE TITLE
[Documentation] Update the installation docs to make the process clearer

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/catalyst#382]
- [x] Rewrite the 'compile from source' section to have subsections per OS, allowing users to easily see together all the commands to run.

- [x] Make sure it is clear that for MacOS users, cmake, rust, and ninja have to be installed, as well as how to install XCode. #377

- [x] On MacOS + anaconda, the default python path is correctly set to the environment python, but python3 (may) point to `usr/bin/python3` (verify this). This can cause the tests to fail, because PyTest is using the wrong Python version. In #377, the command `PYTHON=/Users/username/anaconda3/envs/envname/bin/python make clean-all all` was used.

- [x] On Ubuntu, specify that `libstdc++-dev` needs to be installed

**Comment by dime10** [comment]
> On MacOS + anaconda, the default python path is correctly set to the environment python, but python3 (may) point to usr/bin/python3 (verify this). This can cause the tests to fail, because PyTest is using the wrong Python version. In https://github.com/PennyLaneAI/catalyst/issues/377, the command PYTHON=/Users/username/anaconda3/envs/envname/bin/python make clean-all all was used.

We tried to verify this but unfortunately couldn't reproduce. Both on macos and linux, with both conda and venv the Python from the active environment was picked up. The only exception is when the conda environment was created without specifying a Python version (just `conda create -n myenv`), but in that case `envs/myenv/bin` was empty anyways, so there is no active Python executable anyways.

> On Ubuntu, specify that libstdc++-dev needs to be installed

Do you have some context for this?

**Comment by josh146** [comment]
> We tried to verify this but unfortunately couldn't reproduce. 

Ah 🤔 If I recall, it was @Qottmann who reported this.

> On Ubuntu, specify that libstdc++-dev needs to be installed

Yep, this issue was reported by @dwierichs. He had run

```
sudo apt install clang lld ccache libomp-dev ninja-build make cmake
```

Then, running `make all` was resulting in the error

```
cannot find -lstdc++: No such file or directory
```

However, @dwierichs did not have `g++` previously installed on his system, and apt installing `clang` was not pulling in `libstdc++`. He searched the internet, and [came across this post](https://discourse.llvm.org/t/usr-bin-clang-is-not-able-to-compile-a-simple-test-program/72889/3), which recommended installing `g++-12` in order to pull in `libstdc++-dev`.

This then resolved the error.

My assumption here is that by including `libstdc++-dev` in the `apt` list, we will resolve this issue for other users.

**Comment by Qottmann** [comment]
>> We tried to verify this but unfortunately couldn't reproduce.

> Ah 🤔 If I recall, it was @Qottmann who reported this.

Definitely possible that I had some _other_ python version installed before installing conda (in fact must be no?). Might still be valuable to someone installing to check their `which python3` path and make sure its pointing to the correct python version/env they want.

**Comment by dime10** [comment]
> Definitely possible that I had some other python version installed before installing conda (in fact must be no?).

Yes on Ubuntu there is always at least one version of Python installed (the "system Python").

I couldn't reproduce the issue where `which python3` didn't pick up the version active in the conda/venv environment, but we can add a reference to this problem in a "known issues" section. Thanks for the suggestion!

**Comment by dime10** [comment]
> My assumption here is that by including libstdc++-dev in the apt list, we will resolve this issue for other users.

I'm a bit torn on this one. Looking at the `clang` package on ubuntu, it includes `libstc++` as a dependency: https://packages.ubuntu.com/jammy/clang-14
This makes sense because it is a core requirement for any compiler to have an implementation of the standard library for their programming language available.

So to me this indicates there is a problem with the particular system setup, and there could be **many** such problems and causes depending on OS, compiler, etc. We simply can't anticipate all issues arising from setting up a working C++ toolchain. 
But, I think adding this to a known potential issue section is reasonable, and we will also be adding a bit more information about supported compiler versions, as this has come up in a separate issue.

**Comment by josh146** [comment]
@dime10 as I was writing out my comment above, it did strike me as odd (that you could install `clang` without installing `libstdc++0-dev`!).

But I like the idea of a 'potential issues' section, where we can write potential error messages and the solution (if quick)

**Comment by rauletorresc** [comment]
Quoting @erick-xanadu "Pointing to the ticket where the rust dependency was removed: https://github.com/PennyLaneAI/catalyst/pull/470"
Hence, the second task can be considered as done.
