### ISSUE TITLE
Error - CHECK-NEXT: is not on the line after the previous match

### ISSUE THREAD

**Issue by vincentmr** [PennyLaneAI/catalyst#389]
#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)
All test passing.

* *Actual behavior:* (What actually happens)
`mlir-pdll-lsp-server/completion.test` fails with `CHECK-NEXT: is not on the line after the previous match`. See 
[build-log.txt](https://github.com/PennyLaneAI/catalyst/files/13565007/build-log.txt) for more details.

* *Reproduces how often:* (What percentage of the time does it reproduce?)
100%

* *System information:* (post the output of `import pennylane as qml; qml.about()`)
```
Name: PennyLane
Version: 0.33.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /tmp/catalyst/venv/lib/python3.10/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: amazon-braket-pennylane-plugin, PennyLane-Lightning, PennyLane-Lightning-Kokkos

Platform info:           Linux-5.15.0-88-generic-x86_64-with-glibc2.31
Python version:          3.10.13
Numpy version:           1.26.2
Scipy version:           1.11.4
Installed devices:
- braket.aws.ahs (amazon-braket-pennylane-plugin-1.23.0)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.23.0)
- braket.local.ahs (amazon-braket-pennylane-plugin-1.23.0)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.23.0)
- lightning.kokkos (PennyLane-Lightning-Kokkos-0.33.1)
- default.gaussian (PennyLane-0.33.1)
- default.mixed (PennyLane-0.33.1)
- default.qubit (PennyLane-0.33.1)
- default.qubit.autograd (PennyLane-0.33.1)
- default.qubit.jax (PennyLane-0.33.1)
- default.qubit.legacy (PennyLane-0.33.1)
- default.qubit.tf (PennyLane-0.33.1)
- default.qubit.torch (PennyLane-0.33.1)
- default.qutrit (PennyLane-0.33.1)
- null.qubit (PennyLane-0.33.1)
- lightning.qubit (PennyLane-Lightning-0.33.1)
```

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by rauletorresc** [comment]
This issue has not been experienced lately. Closing.
