### ISSUE TITLE
Cannot compile Lightning with Clang-10

### ISSUE THREAD

**Issue by vincentmr** [PennyLaneAI/catalyst#391]
#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)
Lightning compiles without fault.

* *Actual behavior:* (What actually happens)
Lightning's AVX kernels do not compile. See 
[build-log-10.txt](https://github.com/PennyLaneAI/catalyst/files/13565771/build-log-10.txt) for more details.

* *Reproduces how often:* (What percentage of the time does it reproduce?)
100%

* *System information:* (post the output of `import pennylane as qml; qml.about()`)
On Ubuntu 20.04, `sudo apt install clang lld ccache libomp-dev ninja-build make cmake` installs `clang++-10` which fails to compile the AVX kernels. `clang++-16` works fine on the same system. 

For the record
```
Name: PennyLane
Version: 0.33.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /tmp/catalyst/venv2/lib/python3.11/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: amazon-braket-pennylane-plugin, PennyLane-Lightning, PennyLane-Lightning-Kokkos

Platform info:           Linux-5.15.0-88-generic-x86_64-with-glibc2.31
Python version:          3.11.6
Numpy version:           1.26.2
Scipy version:           1.11.4
Installed devices:
- braket.aws.ahs (amazon-braket-pennylane-plugin-1.23.0)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.23.0)
- braket.local.ahs (amazon-braket-pennylane-plugin-1.23.0)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.23.0)
- lightning.kokkos (PennyLane-Lightning-Kokkos-0.33.1)
- default.gaussian (PennyLane-0.33.1)
- default.mixed (PennyLane-0.33.1)
- default.qubit (PennyLane-0.33.1)
- default.qubit.autograd (PennyLane-0.33.1)
- default.qubit.jax (PennyLane-0.33.1)
- default.qubit.legacy (PennyLane-0.33.1)
- default.qubit.tf (PennyLane-0.33.1)
- default.qubit.torch (PennyLane-0.33.1)
- default.qutrit (PennyLane-0.33.1)
- null.qubit (PennyLane-0.33.1)
- lightning.qubit (PennyLane-Lightning-0.33.1)
```

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by dime10** [comment]
Hi @vincentmr, should this issue have been opened in the lightning repository? Or is there something we can fix on the Catalyst side?

**Comment by vincentmr** [comment]
I think I opened this issue back when the whole company was trying to blindly follow the install-Catalyst-from-source instructions and see what happens. This can probably be closed if no one else reported this.
