### ISSUE TITLE
[BUG] Unexpected state ordering in counts

### ISSUE THREAD

**Issue by lillian542** [PennyLaneAI/catalyst#394]
Not sure if this should be treated as a bug or a documentation update.

#### Issue description

* *Expected behavior:*

Consider the circuit

```
@qml.qnode(qml.device("lightning.qubit", wires=2, shots=1000))
def counts():
    qml.RX(np.pi/2, 0)
    qml.RX(np.pi/4, 1)
    return qml.counts()
```

In plain Pennylane, the 1st number in the string represents qubit 0, and the second qubit 1:

```
>>> counts()
{'00': 437, '01': 80, '10': 423, '11': 60}
```

I would expect the same from Catalyst.

* *Actual behavior:*

Using the method suggested the catalyst docs (see first example [here](https://docs.pennylane.ai/projects/catalyst/en/stable/dev/quick_start.html#measurements)) to convert the Catalyst indices to states, qubit 0 and 1 are swapped when using Catalyst:
```
>>> basis_states, count_res = qjit(counts)()
>>> {format(int(state), '01b'): count for state, count in zip(basis_states, count_res)}
{'0': 393, '1': 463, '10': 62, '11': 82}
```
The missing padded zeros on the left hand side are inconvenient, but the swapping of 01 and 10 is the main issue.

* *Reproduces how often:*
100%

* *System information:* 
pl dev and catalyst dev

**Comment by dime10** [comment]
Thanks for reporting this! Ideally we'll find a better way to return counts from Catalyst functions. With PyTree support, it might now be possible to just return the same dictionary that PennyLane returns :)

The other problem is the classic issue of endianness with quantum bit strings, always a headache 😞

**Comment by dime10** [comment]
Just to a minor comment on the second point raised in this issue (the endianness is fixed by the linked PR):

The get the padding right you have to set the number of qubits in the formatter string. The docs example only has one qubit, so `format(int(state), '01b')` gives the correct results. For your example with 2 qubits you would have to use `format(int(state), '02b')`.
