### ISSUE TITLE
Support compile-time function arguments via `static_argnums`

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#461]
### Context

We would like to allow users to compile a function with `@qjit` without requiring that all arguments to the function have a jit-compatible type. Typically, all built-in numeric types (like `int` and `float`) as well as JAX/NumPy arrays can be compiled as arguments to a function, but when it comes to custom Python classes these will usually raise a compilation error. ("usually" because classes implementing the [PyTree protocol](https://jax.readthedocs.io/en/latest/pytrees.html) are also supported)

For example, the following program will currently raise an error:

```py
import pennylane as qml
from catalyst import *
from dataclasses import dataclass

@dataclass
class MyClass:
  val: int

@qjit
def f(
  x: int,
  y: MyClass,
):
  return x + y.val
```

```pycon
TypeError: Unsupported argument type: <class 'type'>
```

Now a workaround for this is to capture the values of such types directly from the outside scope, instead of passing them to the function as an argument:

```py
y = MyClass(5)

@qjit
def f(
  x: int,
):
  return x + y.val
```

This can be inconvenient, because it requires redefining the function whenever the value of the custom type changes. For convenience, we would like to allow passing such arguments to a jit-compiled function, knowing that those values are treated as compile-time constants (same as when capturing them from the outside scope).

### Goal

We would like to introduce a new keyword `static_argnums` to our `@qjit` decorator. The keyword would act the same as the one employed by JAX (see [jax.jit docstring](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html)). The parameter would be used as follows:

```py
@qjit(static_argnums=1)
def f(
  x: int,
  y: MyClass,
):
  return x + y.val
```

Requirements:
- the `static_argnums` parameter should accept an integer or an iterable of integers
- the integers indicate which argument, by position, should be treated as static
- static arguments are assumed to be hashable
- when a different static argument value is supplied to the function than during first compilation, the function is re-compiled
- using static arguments should bypass AOT compilation (triggered when type hints are provided for arguments), since an actual value is required for the argument

### Technical details

- The `@qjit` decorator indicates the entry point of a compiled function. The decorator must be modified to accept the new parameter.
https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/compilation_pipelines.py#L827-L834
- Initialization of the `QJIT` class triggers a check for AOT mode.
https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/compilation_pipelines.py#L488
- Calling a `QJIT` object processes provided arguments and launches the tracing procedure (see below). Some work would likely happen at this stage, like identifying static arguments, having a mechanism to check if their value changed, and forwarding the information about static arguments to the tracing procedure. Tracing is triggered by a call to [get_mlir](https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/compilation_pipelines.py#L563), followed by [trace_to_mlir](https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/jax_tracer.py#L327).
https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/compilation_pipelines.py#L690
- From there, we interface with the JAX framework to actually perform tracing and generate a representation of the Python function suitable for compilation. This can be done via the [make_jaxpr](https://jax.readthedocs.io/en/latest/_autosummary/jax.make_jaxpr.html) function, but we employ a slightly modified version:
https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/utils/jax_extras.py#L465-L468
  If you compare to the version provided by JAX (see `make_jaxpr` link), some of the arguments in the signature have been stripped, including the `static_argnums` parameter. The function should be modified to accept this parameter again (referring to the source of the [original function](https://jax.readthedocs.io/en/latest/_modules/jax/_src/api.html#make_jaxpr) should be helpful here).

**Tracing**  is the process by which a Python function is captured into a program representation. Having a program representation can be very useful for transformations (like gradients), and is a requirement for compilation. Catalyst uses the JAX framework to generate JAXPR as an intermediate program representation from a Python user function. This representation contains both PennyLane, (JAX) NumPy, and built-in Python operations, from which we generate the main representation for our compiler in MLIR.

_Note that this issue does not require installing Catalyst from source. The PyPI wheel can simply be downloaded and installed/extracted, and the Python files modified in-place._

**Comment by tzunghanjuang** [comment]
Hi all! I am happy to tackle this issue. 

I would like to confirm if I can assume that the `__hash__` method is always implemented. The requirement says that static arguments are hashable, but `MyClass` in the example does not have the `__hash__` method. 

The compilation process involves converting data to NumPy arrays within [args_to_memref_descs](https://github.com/PennyLaneAI/catalyst/blob/e4c2715a9298aa88dd0ac2fca54f3e909c6fdfd7/frontend/catalyst/compilation_pipelines.py#L423). Can I also assume that the `__array__` method is always implemented?

My thought is to store each static argument's hash value in a `QJIT` object to check if any static argument is changed. [jax.jit docstring](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html) mentions that static arguments should be immutable, but we do not have that assumption here. I am not sure if I should handle cases with changing attribute values, like the following example. In scenarios with mutable objects, maybe we have to store a deep copy or force classes to have a method to check if any attribute value is changed.
```python
@qjit(static_argnums=1)
def f(
  x: int,
  y: MyClass,
):
  return x + y.val

z = MyClass(5)
f(1, z)
z.val = 6
f(1, z)
``` 

For re-compilation, I am also uncertain if we need to store previously compiled functions to prevent repetitive compilation.
```python
f(1, MyClass(5))
f(1, MyClass(6)) // re-compile
f(1, MyClass(5)) // re-compile or use stored compiled function?
```

**Comment by tzunghanjuang** [comment]
Hi @dime10, thank you for the clarification. It is very helpful!

> This is a good question, I noticed this too in the JAX docs but I think as long as the mutation is reflected in the hash value (additional assumption) it should work with the proposed system. What do you think?

I see. If the hash value can reflect the mutation, the approach should work. Thank you very much.
