### ISSUE TITLE
Canonicalize MLIR output from JAX before lit testing

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#48]
The MLIR obtained after tracing and stored in the `CompilationPipeline.mlir` attribute contains lots of redundant/mhlo-specific operations, making it more difficult to read but more importantly difficult to test.

We should run the `-canonicalize` pass on this representation to obtain a compact and consistent representation for testing and further processing.

**Comment by dime10** [comment]
Just checking but @pengmai you had a PR for this once JAX has been updated right?

**Comment by pengmai** [comment]
Yup, it'll take a little bit to write up but I'll be able to switch out the subprocess driver with the MLIR Python bindings once the update goes through.

**Comment by erick-xanadu** [comment]
This was fixed with #172
