### ISSUE TITLE
[Frontend] Support decompositions without creating tapes (and instead creating new operations)

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#486]
Have a nice interface for creating `qml.Cond`, `qml.ForLoop`, `qml.WhileLoop` without using the queue.

PL is moving away from using the queue when implementing decompositions. So, to help PL developers, we should be able to construct these operations and use these operations during decomposition.

**Comment by dime10** [comment]
Chatted with @josh146 about this and providing access to the underlaying PennyLane operator via `cond_fn.operation` or similar would be sufficient. The main concern is to allow PL developers to define decompositions without queuing (as the overhead can add up), but allowing users to write decompositions/transforms like they write normal programs is actually a nice feature.

`qml.Cond`, `qml.ForLoop`, ... style interfaces which return the operator instance would conflict with the classical return values, which may be ok in situations where there are none, but then we would also have to support yet another user interface for control flow.

**Comment by paul0403** [comment]
saying something so David knows my github
