### ISSUE TITLE
Replace JAXopt with Optax

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/catalyst#499]
JAXopt is going to be merged into Optax. 
https://github.com/google/jaxopt?tab=readme-ov-file#%EF%B8%8F-we-are-in-the-process-of-merging-jaxopt-into-optax-because-of-this-jaxopt-is-now-in-maintenance-mode-and-we-will-not-be-implementing-new-features-%EF%B8%8F

**Comment by dime10** [comment]
Thank you raising this issue!

**Comment by dime10** [comment]
This was completed in #808 :)
