### ISSUE TITLE
[Frontend] Catalyst control flow is unsupported with `qml.ctrl` and `qml.adjoint`

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#52]
Passing functions to the `qml.ctrl` and `qml.adjoint` meta-operations which contain Catalyst control flow primitives is currently unsupported. The following example demonstrates the issue for the `for_loop` op:

```py
import pennylane as qml
from catalyst import qjit, for_loop

def inner():
    @for_loop(0, 10, 1)
    def loop(j):
        qml.X(0)
    loop()

@qml.qnode(device=qml.device("lightning.qubit", wires=2, shots=1))
def outer():
    qml.ctrl(inner, control=0)()
    return qml.sample()

print(qjit(outer)())
```

**Comment by josh146** [comment]
@dime10 from a technical POV, what is the best way to support this?

**Comment by dime10** [comment]
> @dime10 from a technical POV, what is the best way to support this?

I'm not familiar enough with what `qml.adjoint` and `qml.ctrl` do internally to say.

I know that a quantum control modifier can typically just be propagated into the body of functions and applied to all gates within. Presumably, given that classical operations cannot be quantum-controlled, performing this propagation only on the quantum gates would match the intended meaning by the programmer.
The adjoint modifier is a bit more nuanced, as you'd also need to reverse the control flow graph of such a function.

How are these considerations handled in PennyLane? Are the modifiers simply propagated to the resulting quantum tape no matter how it is constructed within the body of the function?

**Comment by dime10** [comment]
This could also be implemented at the MLIR level by adding such decompositions there instead of in the frontend. We would need to first natively represent `control` and `adjoint` in the IR however, before being able to do so.

**Comment by josh146** [comment]
At the moment, `qml.adjoint` and `qml.ctrl` simply create a 'wrapper' object that specifies 'this is the adjoint/control of the following operation'. That is, they are symbolic representations. In the case of ctrl, it also includes additional information such as the control wires and control values.

Only later, if a device says 'I don't support symbolic operations like adjoint or control', PennyLane will attempt to decompose/expand out these symbolic ops. E.g., `adjoint(RX(0.5))` will be replaced with `RX(-0.5)`.

> We would need to first natively represent control and adjoint in the IR however, before being able to do so.

I think this makes a lot of sense. Especially with `adjoint`, as we sometimes encounter operations where there is no obvious representation of the adjoint gate in the existing gate set. E.g., `adjoint(S)`.

**Comment by josh146** [comment]
> How are these considerations handled in PennyLane? Are the modifiers simply propagated to the resulting quantum tape no matter how it is constructed within the body of the function?

Yes, I think so

**Comment by dime10** [comment]
Well for single gates it's straightforward, but when thinking about applying `adjoint`/`ctrl` to functions it becomes more difficult.

I just tested this piece of code in PennyLane and seems to properly invert the operation order, which is easier when you are only dealing with a flat tape 😅

```py
import pennylane as qml

def func(x, y):
    qml.RX(x, wires=0)
    qml.RY(y, wires=0)

qml.adjoint(func)(0.1,0.2)
```
```pycon
>>> [Adjoint(RY(0.2, wires=[0])), Adjoint(RX(0.1, wires=[0]))]
```

> > We would need to first natively represent control and adjoint in the IR however, before being able to do so.
>
> I think this makes a lot of sense. Especially with adjoint, as we sometimes encounter operations where there is no obvious representation of the adjoint gate in the existing gate set. E.g., adjoint(S).

We can work this into the roadmap for next quarter.

**Comment by josh146** [comment]
> I just tested this piece of code in PennyLane and seems to properly invert the operation order, which is easier when you are only dealing with a flat tape 😅

And this logic was buggy for a very long time 😅 

I wonder if we could preserve `adjoint(qfunc)` as a symbolic instruction set until we get down to MLIR? and then dealing with propagating adjoints/controls could be done during the lowering passes, if needed by the device?*

---

\* This also ties into the work we'll need to do to ensure devices can communicate upwards to the compilation pipeline what passes they need/don't need.

**Comment by dime10** [comment]
Support for this was added in Catalyst v0.3.0 :)
