### ISSUE TITLE
Store correct JAX representation in QJIT object

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#520]
[In this function:](https://github.com/PennyLaneAI/catalyst/blob/main/frontend/catalyst/jax_tracer.py#L330-L363)

```python

def trace_to_mlir(func, static_argnums, abstracted_axes, *args, **kwargs):
    # ... snip ...
    with EvaluationContext(EvaluationMode.CLASSICAL_COMPILATION):
        make_jaxpr_kwargs = {"static_argnums": static_argnums, "abstracted_axes": abstracted_axes}
        jaxpr, out_type, out_tree = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)

    # We remove implicit Jaxpr result values since we are compiling a top-level jaxpr program.
    jaxpr2, out_type2 = jaxpr_remove_implicit(jaxpr, out_type)
    module, context = jaxpr_to_mlir(func.__name__, jaxpr2)
    return module, context, jaxpr, out_type2, out_tree
```

we obtain a jaxpr representation from `make_jaxpr` and then we proceed to do some post-processing of it.

I think we are returning the wrong jaxpr (it should be jaxpr2) and we can replace the names to appropriately be called:

```python
def trace_to_mlir(func, static_argnums, abstracted_axes, *args, **kwargs):
    # ... snip ...
    with EvaluationContext(EvaluationMode.CLASSICAL_COMPILATION):
        make_jaxpr_kwargs = {"static_argnums": static_argnums, "abstracted_axes": abstracted_axes}
        jaxpr, out_type, out_tree = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)

    # We remove implicit Jaxpr result values since we are compiling a top-level jaxpr program.
    jaxpr, out_type = jaxpr_remove_implicit(jaxpr, out_type)
    module, context = jaxpr_to_mlir(func.__name__, jaxpr)
    return module, context, jaxpr, out_type, out_tree
```

**Comment by dime10** [comment]
@grwlf Any thoughts on this?

**Comment by dime10** [comment]
@erick-xanadu Wouldn't the treedef (`out_tree`) need updating along with the abstract values (`out_type`)?

**Comment by erick-xanadu** [comment]
@dime10 I am not sure. I think `out_tree` should be preserved as that is what the user expects.

**Comment by grwlf** [comment]
> @grwlf Any thoughts on this?

I think there are no errors here. Consider the following program:

``` python
@qjit(keep_intermediate=True)
def fun(a):
    r = jnp.ones((a + 1,), dtype=int)
    return r
```
The correct Jaxpr of it is
```
{ lambda ; a:i64[]. let
    b:i64[] = add a 1
    c:i64[b] = broadcast_in_dim[broadcast_dimensions=() shape=(None,)] 1 b
  in (b, c) }  // <--------- Note two return values.
```
Note that `b` is the calculated dimension variable to be returned along with its tensor.
But since it is a top-level Jaxpr, we don't need the dimension anymore, because we don't add any dimension calculations and MLIR tensors carry dimensions internally. So we remove output implicit variables just before getting the StableHLO code. The corresponding IR is

``` mlir
module @fun {
  func.func public @jit_fun(%arg0: tensor<i64>) -> tensor<?xi64> attributes {llvm.emit_c_interface} {
    %0 = stablehlo.constant dense<1> : tensor<i64>
    %1 = stablehlo.add %arg0, %0 : tensor<i64>
    %2 = stablehlo.convert %1 : (tensor<i64>) -> tensor<i32>
    %3 = stablehlo.reshape %2 : (tensor<i32>) -> tensor<1xi32>
    %4 = stablehlo.dynamic_broadcast_in_dim %0, %3, dims = [] : (tensor<i64>, tensor<1xi32>) -> tensor<?xi64>
    return %4 : tensor<?xi64>  // <-------  Note: only one return value
  }
}
```

**Comment by erick-xanadu** [comment]
> I am not sure: its output might contain unlisted Jaxpr variables (in tensor shapes).

By unlisted you mean that the jaxpr contains a variable that will be eliminated via dead code elimination? (Similarly to why we have `_no_cleanup_deadvars`?)

I think ideally the jaxpr we produce should be valid. I understand that the moment it was decided to remove this return value, we deviated from that. Do you remember why this return value was removed?

**Comment by dime10** [comment]
To summarize the resolution we came to:
- the jaxpr _with_ implicit results will be the canonical representation at that level, in order to avoid potentially "incorrect" jaxpr in downstream applications
- filtering implicit args from the jaxpr is a pre-processing step to the mlir lowering only
- the `out_type` after filtering will be removed since it is redundant (only contains `(..., True)` entries)
