### ISSUE TITLE
Catalyst's sample returns floats instead of ints

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#538]
When sampling from the computational basis, Catalyst still returns floats (the general observable case) whereas PennyLane returns ints. The output type can be converted from the frontend for a more unified user experience.

---
_Original message:_

```c
void __catalyst__qis__Sample(MemRefT_double_2d *result, int64_t shots, int64_t numQubits, ...)
```

It should be 

```c
void __catalyst__qis__Sample(MemRefT_int_2d *result, int64_t shots, int64_t numQubits, ...)
```

**Comment by dime10** [comment]
It was designed as a float so that we can support observable eigenvalue sampling with the same operation, see here: https://github.com/PennyLaneAI/catalyst/blob/87aed48b3be0c635f7d1530418e3365d40f9a669/mlir/include/Quantum/IR/QuantumOps.td#L548-L550

**Comment by erick-xanadu** [comment]
What I understand from the snippet provided is that the return value depends on the operand. Can't we cast the return value immediately afterwards?

**Comment by dime10** [comment]
Oops sorry, that snippet is irrelevant. You can see the return type though is a float for the reason I mentioned:
https://github.com/PennyLaneAI/catalyst/blob/87aed48b3be0c635f7d1530418e3365d40f9a669/mlir/include/Quantum/IR/QuantumOps.td#L581-L584

I agree though that the frontend can generate code to cast the result conditionally, which would be more user friendly. The same could be done to post-process the counts format that is produced at the low-level.

**Comment by erick-xanadu** [comment]
I don't understand the reason. Are you saying that this return type is necessary because the value might be used by another operation that requires F64s? It is alright, not really super necessary, but it is inconsistent with PL. And also, bits can be strongly packed. I suppose we don't need to return Int64, it could be a bit array. This would reduce the amount of memory transfers.

**Comment by erick-xanadu** [comment]
In the runtime we are converting them to F64:

```c++
void LightningSimulator::Sample(DataView<double, 2> &samples, size_t shots)
{
    auto li_samples = this->GenerateSamples(shots);

    RT_FAIL_IF(samples.size() != li_samples.size(), "Invalid size for the pre-allocated samples");

    const size_t numQubits = this->GetNumQubits();

    // The lightning samples are layed out as a single vector of size
    // shots*qubits, where each element represents a single bit. The
    // corresponding shape is (shots, qubits). Gather the desired bits
    // corresponding to the input wires into a bitstring.
    auto samplesIter = samples.begin();
    for (size_t shot = 0; shot < shots; shot++) {
        for (size_t wire = 0; wire < numQubits; wire++) {
            *(samplesIter++) = static_cast<double>(li_samples[shot * numQubits + wire]);
        }
    }
}

```

**Comment by dime10** [comment]
So PennyLane has two modes for the sample op, one with an observable and one without. When provided with an observable, the returned values are taken from the set of eigenvalues of the observable, which could be floating point numbers. See the example in the sample docs:
```py
    return qml.sample(qml.PauliY(0))
Executing this QNode:

>>> circuit(0.5)
array([ 1.,  1.,  1., -1.])
```

So this op is set to always return floats because it this the more general datatype and causes no loss of information (1-bit integers can easily be represented exactly as floats).

**Comment by erick-xanadu** [comment]
I ran the example, the example is wrong. We return integers.

```python
import pennylane as qml

dev = qml.device("default.qubit", wires=2, shots=4)

@qml.qnode(dev)
def circuit(x):
    qml.RX(x, wires=0)
    qml.Hadamard(wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.sample(qml.PauliY(0))

print(circuit(0.5))

dev = qml.device("default.qubit", wires=2, shots=4)

@qml.qnode(dev)
def circuit(x):
    qml.RX(x, wires=0)
    qml.Hadamard(wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.sample()

print(circuit(0.5))
```

```
[ 1 -1 -1 -1]
[[0 0]
 [0 0]
 [0 0]
 [0 1]]
```

**Comment by dime10** [comment]
Hmm maybe something changed internally which now generates the eigenvalues of Paulis as integers, but it doesn't matter. In general, Observables will have real eigenvalues.

**Comment by erick-xanadu** [comment]
Alright then! Should we mark this as wontfix and close? Happy to let you decide how best to handle this. :)

**Comment by dime10** [comment]
Well there is an improvement we could make from the frontend in order to match what PL produces, in a similar vein to #341.
