### ISSUE TITLE
Remove redundant code from `GlobalPhase` jax primitive

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#586]
`GlobalPhase` jax primitive allows for multiple classical parameters, but only one is needed. We can delete this.

**Comment by dime10** [comment]
We can also delete the target wires and associated code in the frontend, I remember this was left in.

**Comment by dime10** [comment]
> This appears to be not true. Templates test show global phase with wires. Something (could be decomposition) is adding wires to global phase.

What purpose would that serve since we are just discarding them?

**Comment by erick-xanadu** [comment]
> What purpose would that serve since we are just discarding them?

What purpose would it serve to add wires to global phase? I am assuming just to keep consistency and generality. All I know is that at the moment of binding, an assertion I placed to make sure there are no wires in the global phase, but there are. If I ignore this assertion, then the dictionary which keeps track of the wires gets out of sync. I can investigate more, but I think this is an issue that should be addressed not in this housekeeping item, but by looking more closely into the quantum register promise.

**Comment by erick-xanadu** [comment]
I added more context here: https://github.com/PennyLaneAI/catalyst/pull/640/commits/0d25625453363212624562df9c8bed37ae696699
