### ISSUE TITLE
Support new SProd

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#587]
https://github.com/PennyLaneAI/pennylane/pull/5287

Superseded by: https://github.com/PennyLaneAI/pennylane/pull/5885

**Comment by dime10** [comment]
Labelling this as a "bug" since it needs to be fixed before the next PL ecosytem release.

**Comment by erick-xanadu** [comment]
I think this was fixed with #935, @dime10 can you also confirm?

**Comment by dime10** [comment]
I think so? 😅
