### ISSUE TITLE
[JAX] Missing support for sub-array updates with `array.at[]`

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#65]
At the moment there seems to be no way to lower the scatter operation from the MHLO dialect into standard MLIR dialects used by us. This op is generated by JAX for their ["in-place" array updates](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#array-updates-x-at-idx-set-y), see the following example:

```py
from jax import numpy as jnp
from catalyst import qjit

@qjit
def test(idx: int):
    res = jnp.array([0, 0, 0])
    res = res.at[idx].add(1)
    return res

test(1)
```

The example fails with the following error message (raised when `quantum-opt` tries to parse the output from the `mlir-hlo-opt` tool):

```sh
/tmp/tmps5we6mfm/test.nohlo.mlir:33:24: error: operation being parsed with an unregistered dialect. If this is intended, please use -allow-unregistered-dialect with the MLIR tool used
    %8 = "mhlo.scatter"(%cst_1, %expanded, %cst) ({
```

This not necessarily an issue within Catalyst, and may need to be resolved upstream in the MLIR-HLO project.

Note: The tensor dialect seems to have a [scatter op](https://mlir.llvm.org/docs/Dialects/TensorOps/#tensorscatter-mlirtensorscatterop).

--- 

A workaround for the above example may be achieved as followed:
```py
from jax import numpy as jnp
from catalyst import qjit

@qjit
def test(idx: int):
    res = jnp.array([0, 0, 0])
    additions = jnp.identity(3)
    res = res + additions[idx]
    return res

test(1)
```

**Comment by grwlf** [comment]
I have discovered the following facts which may be relevant to this issue:

1. The [gml_st_scattter.mlir](https://github.com/tensorflow/mlir-hlo/blob/9a5d9a6805e5860ad13688df89b779b65c946af8/tests/end2end/gml_st_scatter.mlir#L1) describes the procedure of lowering `scatter`s via the [gml_st](https://github.com/tensorflow/mlir-hlo/blob/master/gml_st/README.md) dialect.
2. Following the above procedure, the `--hlo-canonicalize-scatter --legalize-mhlo-to-thlo --hlo-legalize-to-linalg --scalarize` flags applied at the `nohlo` stage turn the relevant `mhlo.scatter` into the following IR:

``` mlir
    ...
    %8 = scf.if %7 -> (tensor<3xi64>) {
      %9 = gml_st.tile [%c0, %c0] [1, 1] [1, 1] : !gml_st.tile<1x1>
      %10 = gml_st.materialize %cst[%9] : tensor<1x1xi64>[!gml_st.tile<1x1>] to i64
      %11 = gml_st.tile [%4] [1] [1] : !gml_st.tile<1>
      %12 = gml_st.materialize %cst_0[%11] : tensor<3xi64>[!gml_st.tile<1>] to i64
      %13 = arith.addi %12, %10 : i64
      %inserted = tensor.insert %13 into %cst_0[%4] : tensor<3xi64>
      scf.yield %inserted : tensor<3xi64>
    } else {
      scf.yield %cst_0 : tensor<3xi64>
    }
```

Hopefully, one could lower `gml_st` ops further into `scf` if we manage to pass `gml_st` through the `quantum-opt` stages.

**Comment by erick-xanadu** [comment]
[Semantics of `stablehlo.scatter`.](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#scatter)

**Comment by grwlf** [comment]
We are going to take a break from this task, here is a brief summary:

The codegen pipeline currently looks like:
* User calls one of the [JAX numpy's top-level .at() operations](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html#jax.numpy.ndarray.at)
* They are lowered to the [jax.lax.scatter](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scatter.html)
* And later to the [MHLO::Scatter](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#scatter)

The `mhlo.scatter` has a rich semantics. Here is its [reference specification in Python](https://gist.github.com/grwlf/a40d20edf2bf8f7debc046ac41a08cd9)  (Sketch). The operation looks more generic than it is originally required by JAX, namely, the **stateful folding** semantics doesn't seem necessary to implement `at` instructions.

The ideas to solve the issue include:
* Use the `thlo -> gml-st -> bufferization -> scf` path which is already present in MHLO. This solution implies legalizing the `gml-st` dialect as a valid `quantum-opt` input and would introduce MHLO as a dependency.
* Implement a custom pass for lowering `mhlo.scatter -> tensor.scatter`. Given the rich semantics of `mhlo.scatter`, this would probably handle only a set of cases we believe are in use by JAX.
* Patch JAX to make it issue a less generic instruction such as `tensor.scatter`.

**Comment by Gopal-Dahale** [comment]
@dime10 Do you know any workaround for 2D arrays 😅 ?

**Comment by dime10** [comment]
Hi @Gopal-Dahale, it depends on what you are doing exactly, but the idea would be to express your computation without explicitly setting elements of a tensor.
The workaround for the addition example makes use of a constant array with the same shape as the original. Zeros are located at all the positions you want to leave unchanged, and non-zero entries contain the value you want to add. This should work the same in 2 dimensions, let me know if you any issues with it :)

Hopefully we can get a proper fix for this issue in the near future 🤞

**Comment by josh146** [comment]
Hey @Gopal-Dahale! Do you mind sharing a minimal example of the code you are trying to run with catalyst that requires `array.at()` :) this will help us work out the best fix

**Comment by Gopal-Dahale** [comment]
A minimal example would be similar to the [Magic State DIstillation](https://docs.pennylane.ai/projects/catalyst/en/latest/demos/magic_distillation_demo.html#Purification-algorithm) present in docs. In the loop, in addition to performing mid-circuit measurements, I also want to store these measurement values across iterations and then return this array of measured values. For this I will require a 2D array as I cannot use variable sized arrays in `jit`. I hope this helps.

**Comment by dime10** [comment]
> A minimal example would be similar to the [Magic State DIstillation](https://docs.pennylane.ai/projects/catalyst/en/latest/demos/magic_distillation_demo.html#Purification-algorithm) present in docs. In the loop, in addition to performing mid-circuit measurements, I also want to store these measurement values across iterations and then return this array of measured values. For this I will require a 2D array as I cannot use variable sized arrays in `jit`. I hope this helps.

Thanks for adding some detail @Gopal-Dahale!

Just as a side note, if the number of measurements you want to record is fixed (and not too large), you can actually accumulate the measurements in a list and convert them to an array before returning. This would be an example of that:
```py
@qjit
@qml.qnode(qml.device("lightning.qubit", wires=1))
def func():
    m_list = []
    for i in range(10):
        m_res = measure(0)
        m_list.append(m_res)
    res = jnp.array(m_list)
    return res
```
The downside is that every measurement is a separate instruction and variable in the program, and changing the number of measurements requires recompilation. So I wouldn't recommend it if the number is very large, or if the number of measurements has to depend on a function argument or some other dynamic quantity (it wouldn't be applicable to the MSD while loop for instance, but JAX doesn't let you create an array of arbitrary size anyways).

For reference, the above gives the following JAXPR:
```py
a:bool[10] = func[
  call_jaxpr={ lambda ; . let
      b:AbstractQreg() = qalloc 1
      c:AbstractQbit() = qextract b 0
      d:bool[] e:AbstractQbit() = qmeasure c
      f:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] d
      g:bool[] h:AbstractQbit() = qmeasure e
      i:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] g
      j:bool[] k:AbstractQbit() = qmeasure h
      l:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] j
      m:bool[] n:AbstractQbit() = qmeasure k
      o:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] m
      p:bool[] q:AbstractQbit() = qmeasure n
      r:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] p
      s:bool[] t:AbstractQbit() = qmeasure q
      u:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] s
      v:bool[] w:AbstractQbit() = qmeasure t
      x:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] v
      y:bool[] z:AbstractQbit() = qmeasure w
      ba:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] y
      bb:bool[] bc:AbstractQbit() = qmeasure z
      bd:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] bb
      be:bool[] _:AbstractQbit() = qmeasure bc
      bf:bool[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] be
      bg:bool[10] = concatenate[dimension=0] f i l o r u x ba bd bf
      = qdealloc b
  in (bg,) }
  fn=<QNode: wires=1, device='lightning.qubit', interface='auto', diff_method='best'>
]
```

**Comment by josh146** [comment]
@rmoyard is this one now solved?

**Comment by rmoyard** [comment]
Yes :+1:

**Comment by rmoyard** [comment]
https://github.com/PennyLaneAI/catalyst/pull/273
