### ISSUE TITLE
Support building with conda on macOS

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#677]
#### Issue description

* *Expected behavior:* Following the build instructions should build catalyst correctly when using conda.

* *Actual behavior:* Following these instructions:

1. Created a new environment via the command conda create -n catalyst_test python=3.10 and activated the new environment

```bash
pip install cmake ninja
brew install libomp
cd catalyst
git checkout main
git pull
pip install -r requirements.txt
brew install ccache
make llvm
make mhlo
make enzyme
make dialects
make runtime
pip install -e .
```

didn't work out. Tests didn't finish running with half of the ones the finished failing.

* Tested on MacBook Air, M1 2020, and running macOS Sonoma 14.3.1 (but possibly affects other platforms)

**Comment by rauletorresc** [comment]
So far the commands you wrote worked out on MacOS Monterey, using Conda. Is there something missing? Maybe `make test` or `make test-frontend`?

**Comment by rauletorresc** [comment]
I made another tests under macOS 14.6.1 (Sonoma) in a M2 machine (aarch64) also with Conda. I also ran `make test` and `make test-frontend`.

The installation worked out of the box.

**Comment by rauletorresc** [comment]
@erick-xanadu @dime10 if you both agree, we can close this issue as Solved

**Comment by rauletorresc** [comment]
Closing, as it has not been experienced anymore.
