### ISSUE TITLE
[MLIR] Missing bufferization for `memref.tensor_store`

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#73]
This op is generated in our parameter-shift gradient method (for some cases) and will fail bufferization.

Fixed upstream last month in https://reviews.llvm.org/D144080, so a JAX update on our side should fix the issue.

**Comment by erick-xanadu** [comment]
Let's add tests for this ticket.

**Comment by erick-xanadu** [comment]
Are parameter shift already in pytests enough?
