### ISSUE TITLE
It would be nice to have an interface (or documentation) for accessing the original function of a QJIT object

### ISSUE THREAD

**Issue by paul0403** [PennyLaneAI/catalyst#765]
Say we wish to find the matrix representation of a circuit:
```python
dev = qml.device("lightning.qubit", wires=1)

@qml.qnode(dev)
def f():
	qml.PauliX(0)
	return qml.state()

print(f)
print(qml.matrix(f)())

>>>
<QNode: device='<lightning.qubit device (wires=1) at 0x7ba9e13912a0>', interface='auto', diff_method='best'>
[[0 1]
 [1 0]]
```

but the circuit is `qjit`ted:
```python
@qjit
@qml.qnode(dev)
def f():
	qml.PauliX(0)
	return qml.state()

print(f)
print(qml.matrix(f)())

>>>
<catalyst.jit.QJIT object at 0x70d4abe9fee0>
Traceback (most recent call last):
  File "/home/paul.wang/small_playgrounds_dump/qsvt_demo/original_function.py", line 23, in <module>
    print(qml.matrix(f)())
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/ops/functions/matrix.py", line 205, in matrix
    raise ValueError("wire_order is required by qml.matrix() for quantum functions.")
ValueError: wire_order is required by qml.matrix() for quantum functions.
```

This is because in core PL, a "QJIT object" is not an appropriate operation to pass into `qml.matrix`. The workaround is 
```python
print(qml.matrix(f.original_function)())

>>>
[[0 1]
 [1 0]]
```
by accessing the raw `QJIT.original_function` attribute, but this it is dangerous to expose this to the user, since there could be, say, 
```python
f.original_function = "some garbage"
```
once this door is opened. Perhaps a better UI will be beneficial?

**Comment by paul0403** [comment]
A better solution would be for a ```QJIT``` object to retain all its capabilities of being used as a ```qnode``` object when used in core PL, though I'm not sure how to do that.

**Comment by dime10** [comment]
I think documenting this attribute better is a good idea! I don't think it's necessarily dangerous, we can address the problem you point out with a getter method (`@property`).

The "official" `functools` way of making the wrapped function accessible is via the `__wrapped__` attribute, but I don't know if we want to go with that because the standard library interacts with that attribute in other ways as well.

**Comment by dime10** [comment]
> A better solution would be for a `QJIT` object to retain all its capabilities of being used as a `qnode` object when used in core PL, though I'm not sure how to do that.

A QJIT object is distinctly different from a QNode (it can be classical, quantum, or both), so this is not a good idea.
