### ISSUE TITLE
Getting different values with @qjit

### ISSUE THREAD

**Issue by kaitlinmgili** [PennyLaneAI/catalyst#82]
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/PennyLaneAI/catalyst/issues

If posting a Catalyst issue, delete everything above the dashed line, and fill
in the template. If the issue is a bug, start the title of the issue with [BUG].

If making a feature request, delete the following template and describe, in detail,
the feature and why it is needed.

-------------------------------------------------------------------------------------------------------------

#### Issue description

We use the following collaboration notebook https://colab.research.google.com/drive/1PU-xnvdxVqYE8DKMyJdREyYIdrdVpZvl#scrollTo=OHDvAThytfjI. 

It seems that the "patata" function in this notebook gives us different results depending on whether we do @qjit or not at the top of the function. In the correct solution we should only see 0s or 3s, but with qjit we get different values.

**Comment by erick-xanadu** [comment]
Hi @kaitlinmgili, thanks for the issue! It should be solved and merged relatively quick. @dime10 will be in touch with you then. 

Cheers!
