### ISSUE TITLE
Calculating the sample of an observable kills the kernel

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/catalyst#828]
#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)

I would it to behave the same as the non-qjit analog, returning:
```
tensor([1., 1., 1., 1., 1.], requires_grad=True)
```

Or at least raising an informative error.

* *Actual behavior:* (What actually happens)

Python kernel dies

* *Reproduces how often:* (What percentage of the time does it reproduce?)

every time.

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

master pennylane, recent catalyst (haven't updated in a few weeks)

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

```
dev = qml.device('lightning.qubit', wires=2, shots=5)

@qml.qjit
@qml.qnode(dev)
def circuit():
    qml.Hadamard(0)
    return qml.sample(op=qml.X(0))

circuit()
```

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by dime10** [comment]
Observables are currently unsupported for any MP other than `exp` and `var`: https://docs.pennylane.ai/projects/catalyst/en/stable/dev/quick_start.html#measurements

It might useful to raise an error message at trace time in the meantime though. The verification framework we implemented this quarter should be able to tackle this 🤔 
@lillian542 Do you know if the verification we merged so far checks for unsupported MPs?

**Comment by trbromley** [comment]
> Observables are currently unsupported for any MP other than exp and var

@dime10 is this on the Q3 roadmap, or a candidate for the Q4 tech roadmap?

**Comment by dime10** [comment]
This was just merged, but it was think it was missing the verification of missing features (like sampling observables). @lillian542

**Comment by lillian542** [comment]
@dime10 I forgot about this issue, this won't currently be caught by verification - if Samples is allowed on the device, and the observable is allowed on the device, it will pass. Will be a very minor change, I'll open a PR.
