### ISSUE TITLE
Look into adding support for float32 in callbacks

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#844]
When using float32 as a result type in callbacks the program crashes. I think this is because at some point we assume float64 will be used but float32 was used. If we can preserve user's intention, then it is best to also use float32. For a small temporary solution, we can provide raise an error or do type promotion implicitly.

**Comment by mlxd** [comment]
I think an error here is preferable to implicit promotion, leaving the responsibility on the user to perform the casting for now, at least until end-to-end support for FP32 is added.

**Comment by erick-xanadu** [comment]
Fixed by #916
