### ISSUE TITLE
Change `argnum` to `argnums`

### ISSUE THREAD

**Issue by erick-xanadu** [PennyLaneAI/catalyst#850]
Catalyst grad and jacobian use `argnum` instead of `argnums`.  We should use `argnums` like JAX. Specially since `grad` and `jacobian` fall back to `jax.grad` and `jax.jacobian`.

**Comment by dime10** [comment]
Breaking API change, should be co-ordinated with PennyLane @trbromley

**Comment by erick-xanadu** [comment]
Closed done with #1036
