### ISSUE TITLE
`catalyst.pure_callback` gradients don't work when the VJP function is computed in the `fwd` pass

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/catalyst#852]
I'm attempting to utilize the fact that, if a `jax` function is being used during a callback, `jax.vjp` can be used during the forward pass to generate a VJP and the forward pass result:

```python
def jax_callback(fn, result_type):

    @catalyst.pure_callback
    def callback_fn(*args) -> result_type:
        return fn(*args)

    @callback_fn.fwd
    def callback_fn_fwd(*args):
        ans, vjp_func = catalyst.accelerate(lambda *x: jax.vjp(fn, *x))(*args)
        return ans, vjp_func

    @callback_fn.bwd
    def callback_fn_bwd(vjp_func, dy):
        return catalyst.accelerate(vjp_func)(dy)

    return callback_fn

@qml.qjit
@catalyst.jacobian
def f(x):
    expm = jax_callback(jax.scipy.linalg.expm, jax.ShapeDtypeStruct((2, 2), jnp.float64))
    return expm(x)
```

```pycon
>>> x = jnp.array([[0.1, 0.2], [0.3, 0.4]])
>>> f(x)
TypeError: Callback closure expected type ShapedArray(float64[2,2]) but observed ShapedArray(float64[]) in its return value
```

I've tried other attempts, including:

- Not wrapping the `jax.vjp` call in a `pure_callback`, but still calling `accelerate(vjp_func)`. This gives:
  ```
  UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX
  had a side effect, allowing for a reference to an intermediate value with type int32[]
  wrapped in a DynamicJaxprTracer to escape the scope of the transformation.
  ```

- Not wrapping the `jax.vjp` call in a `pure_callback`, and also not wrapping `vjp_func` in a `pure_callback`. This leads to the kernel crashing.

The only thing that works is the following:

```python
from collections.abc import Sequence

def jax_callback(fn, result_type):

    @catalyst.pure_callback
    def callback_fn(*args) -> result_type:
        return fn(*args)

    @callback_fn.fwd
    def callback_fn_fwd(*args):
        return fn(*args), args

    @callback_fn.bwd
    def callback_fn_bwd(res, dy):
        vjp = catalyst.accelerate(lambda dy, *args: jax.vjp(fn, *args)[1](dy))
        return vjp(dy, *res)

    return callback_fn
```

However, this is not ideal, as the forward pass will be evaluated twice.

**Comment by erick-xanadu** [comment]
Hi Josh, the variable `vjp_func` is local to the `callback_fn_fwd` function. I also do not believe it is possible to pass a function through JAX like you are trying to here:

```python
    @callback_fn.fwd
    def callback_fn_fwd(*args):
        ans, vjp_func = catalyst.accelerate(lambda *x: jax.vjp(fn, *x))(*args)
        return ans, vjp_func
```

What you can do is create a nonlocal vjp_func variable and reference and update it in the forward pass like in one of the tests. E.g.

```python
def jax_callback(fn, result_type):

    vjp_func = None

    @catalyst.pure_callback
    def callback_fn(*args) -> result_type:
        return fn(*args)

    @callback_fn.fwd
    def callback_fn_fwd(*args):
        nonlocal vjp_func
        ans, vjp_func = catalyst.accelerate(lambda *x: jax.vjp(fn, *x))(*args)
        return ans

    @callback_fn.bwd
    def callback_fn_bwd(residuals, dy): # Notice that the residuals is unused and different from vjp_func
        return catalyst.accelerate(vjp_func)(dy)

    return callback_fn
```

The residuals have to be arrays, they cannot be functions. 

You can then cache the `vjp_func` by just checking if it is None or not. I am not sure yet how JAX deals with it. I want to believe they cache it themselves but haven't verified it.

**Comment by josh146** [comment]
Thanks @erick-xanadu! Strangely, it actually does seem to pass through to the `bwd` function, because the `vjp_func` that JAX generates is not a python `function`, but it's a `jax._src.tree_util.Partial` object, which seems to be a valid (callable) Pytree with a JAXPR representation:

https://github.com/google/jax/blob/2b728d55b6054bba8ae26b3523722e80d660e771/jax/_src/tree_util.py#L491-L492

So I'm able to pass this object from `fwd` to `bwd`, but then catalyst either crashes _or_ I get a 'leaked tracer' error 🤔 

Thanks for your tip!

**Comment by dime10** [comment]
I also found it weird to see the `accelerate` calls in the forward and backward passes, but forgot that we don't treat those as callbacks by default.

For the example given, wouldn't it be easier to just call `accelerate` on `fn` if it is jax.jittable,
or are you trying to combine different features for testing purposes? 😅 

>  Strangely, it actually does seem to pass through to the bwd function, because the vjp_func that JAX generates is not a python function, but it's a jax._src.tree_util.Partial object, which seems to be a valid (callable) Pytree with a JAXPR representation:

This is an interesting issue, it may be worth filing a separate bug report for it? Does `Partial` work as a function argument in regular contexts, or is it broken everywhere?

**Comment by josh146** [comment]
> I also found it weird to see the accelerate calls in the forward and backward passes, but forgot that we don't treat those as callbacks by default.

Yep! In this example, `catalyst.accelerate` was a nice shortcut for `pure_callback` but without needing to hardcode in return types, so it's quite convenient that we don't block it on CPUs 😆 

> For the example given, wouldn't it be easier to just call accelerate on `fn` if it is `jax.jittable`,
or are you trying to combine different features for testing purposes?

I'm mostly trying to work out: for functions we know are JAX compatible (and thus `jax.vjp` will work), can we leverage this to automatically register these as VJP rules, without repeating the fwd execution twice?

**Comment by josh146** [comment]
> This is an interesting issue, it may be worth filing a separate bug report for it? Does Partial work as a function argument in regular contexts, or is it broken everywhere?

Seems to be a mix 🤔 In some cases where we allow generic pytrees, it works fine. In other cases, we seem to have Catalyst-specific validation for known JAX types which this will fail to be passed through.

**Comment by dime10** [comment]
> Yep! In this example, catalyst.accelerate was a nice shortcut for pure_callback but without needing to hardcode in return types, so it's quite convenient that we don't block it on CPUs 😆

Yeah definitely seems convenient 😅 

> I'm mostly trying to work out: for functions we know are JAX compatible (and thus jax.vjp will work), can we leverage this to automatically register these as VJP rules, without repeating the fwd execution twice?

That makes sense :) `accelerate` will do that for us once we complete it right?

**Comment by josh146** [comment]
> That makes sense :) accelerate will do that for us once we complete it right?

Yes, that was additional motivation for exploring this (seeing if what we have for `pure_callback` can be re-used easily)

**Comment by dime10** [comment]
@josh146 In summary, is this issue considered user-error or would you like us to implement some changes?

**Comment by erick-xanadu** [comment]
This is closed as the RC candidate has been merged to main.
