### ISSUE TITLE
jvp mention is missing opening backtick

### ISSUE THREAD

**Issue by rauletorresc** [PennyLaneAI/catalyst#912]
jvp mention is missing opening backtick
```
jvp`
```
It should be:
```
`jvp`
```
https://github.com/PennyLaneAI/catalyst/blob/0b8213d58c8bfbd53dc57842b360fcb5767f3dfa/doc/changelog.md?plain=1#L423

**Comment by dime10** [comment]
Might be just as fast to open the PR than the issue? 😄
