### ISSUE TITLE
Align definition of scale factor with Zero-Noise Extrapolation literature

### ISSUE THREAD

**Issue by cosenal** [PennyLaneAI/catalyst#983]
The [`mitigate_with_zne`](https://docs.pennylane.ai/projects/catalyst/en/latest/code/api/catalyst.mitigate_with_zne.html) API in Catalyst accepts a `scale_factors` argument, which represents a range of scalar factors by which the circuit is scaled. 

In the literature of Zero-Noise Extrapolation [^1][^2], a _scale factor_ value $\lambda$ is the ratio between the number of gates of the scaled circuit and the number of gates of the original circuit. However, in the [Catalyst implementation](https://github.com/PennyLaneAI/catalyst/blob/9f8c66353f0240787a394ac725e7ffd239f5a448/mlir/lib/Mitigation/Transforms/MitigationMethods/Zne.cpp#L176), the term scale factor is used to denote the number $n$ of foldings of the circuit.

The relation between the two definitions is $\lambda = 1 + 2n$.

For example, `scale_factor = 1` (i.e., $\lambda=1$, $n=0$) means that the circuit is not folded.
For  `scale_factor = 3` ($\lambda=3$, $n=1$), we have that the circuit is folded once

$$C \rightarrow C(C^{\dagger}C)$$

and the number of gates in the scaled circuit is three times the number of gates in the original circuit.
(See [^2] for a discussion on odd/even/non-integer scale factors.)

-----
This issue is about aligning the definition of scale factor in Catalyst with the literature as above, by either renaming the `scale_factors` argument in the API, or assigning a new meaning to it. 

[^1]: https://arxiv.org/abs/2005.10921
[^2]: https://mitiq.readthedocs.io/en/v0.38.0/guide/zne-3-options.html#what-additional-options-are-available-when-using-zne

**Comment by cosenal** [comment]
Implementation in non-catalyst pennylane, for reference: https://github.com/PennyLaneAI/pennylane/blob/1d220cf6d69cbf60c99c5318b5137b69f7d6d30d/pennylane/transforms/mitigate.py#L214-L217

**Comment by rmoyard** [comment]
I will tackle that in the upcoming days :+1:

**Comment by cosenal** [comment]
Nice, thanks @rmoyard. Please keep me in the review loop of the design and PRs.
Is the plan to do the same as Pennylane, that is, convert the scale factor in a folding factor and keeping the folding as is? Is it going to be in the frontend or in the dialect?

**Comment by rmoyard** [comment]
Yes I think that is the best, I will either add some restrictions because we don't support the fraction scale or just just ignore the fraction scale.

`num_global_folds, _ = _divmod(scale_factor - 1, 2)`

**Comment by cosenal** [comment]
~`num_global_folds`~`num_folds`, since this will have to be the same way for both global and local folding.

**Comment by cosenal** [comment]
Solved by #1120.
I will create a separate issue/feature request for non-integer and fraction scale.
